### PR TITLE
hello microverse pull request

### PR DESCRIPTION
**Pull request by techmoves**
html and css project

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @techmoves 👋,

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f69656d6d596a3332456945655a59766a70712f67697068792e676966
 

Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!🤗

## Highlights✅✅

- [x] GitHub flow 👍
- [x] HTML and CSS file has been added👍


## Required Changes ♻️
- [ ] Nice job implementing the features of this milestone👍 But I think we give your repo a more professional look😉
- First, Kindly use the [Microverse template](https://github.com/microverseinc/readme-template) to give your readme a more professional look😉 don't forget, it is [required ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md)that our project is professionally documented🤗🤗

your readme
readKind

- Kindly write a descriptive summary for your pull request as this will give our project a more professional look👍 a descriptive summary should contain the features or changes you have added to the branch😉😉 kindly make use of[ this lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) as a guideline to implement the changes🤗🤗
- [ ]  I can see you have set up your linters correctly👍 but your stylelint is still failing and it is a requirement that all linter tests must be passed 🤗🤗
linter errors stylelint


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] I suggest you take a look at [this lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to write more descriptive messages as this can improve the professionalism of your project😉😉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by techmoves — COMMENTED** [review]
changes mad ewon another PR

**Review by aamirkhan2478 — COMMENTED** [review]
Hi @techmoves , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] You have submitted a project, which has been merged, so please submit another code review request with the open pull request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by techmoves** [comment]
oops i appologes i noticed after i submitted it but a new PR is on it way

thanks

**Comment by techmoves** [comment]
> …

https://github.com/techmoves/hello-microverse/pull/3

**Comment by techmoves** [comment]
hi [Ibizugbe](https://github.com/Ibizugbe)

it got merged by mistake
here is the pull request

https://github.com/techmoves/hello-microverse/pull/3

**Pull request merged**
